spring:
  application:
    name: service-zuul-server
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    store:
      service-id: service-stores
      path: /api/tienda/**
    cellphones:
      service-id: service-cellphones
      path: /api/cellphones/**
      
ribbon:
 ConnectTimeout: 3000
 ReadTimeout: 10000
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 40000